# Generated by Django 3.1.6 on 2021-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0007_auto_20210215_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
